spring:
  application:
    name: LAN-Transmission-tool
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
server:
  port: 8080
file:
  path:
  count: 10